spring.application.name=ngo-donation-management

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ngo_donation_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=saru@2007
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

server.port=8091

spring.web.resources.static-locations=classpath:/static/
